font_family JetBrainsMono Nerd Font Mono
font_size 14

disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape block

url_style curly

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 20
cursor_blink_interval 0

background_opacity 			0.8
scrollbar_handle_opacity 		0
scrollbar_track_opacity 		0
scrollbar_track_hover_opacity 		0
confirm_os_window_close 		0

sync_to_monitor no


# One Dark by Giuseppe Cesarano, https://github.com/GiuseppeCesarano
# This work is licensed under the terms of the GPL-2.0 license.
# For a copy, see https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html.

foreground #E5E4E2
background #100C08
cursor #cccccc
color0 #282c34
color1 #e06c75
color2 #98c379
color3 #e5c07b
color4 #61afef
color5 #be5046
color6 #56b6c2
color7 #979eab
color8 #393e48
color9 #d19a66
color10 #56b6c2
color11 #e5c07b
color12 #61afef
color13 #be5046
color14 #56b6c2
color15 #abb2bf
selection_foreground #282c34
selection_background #979eab
